@startuml UC019
skinparam actorStyle awesome

actor "Gestionnaire" as Gestionnaire
participant "Système INTRA" as INTRA
participant "CBS (Core Banking System)" as CBS
database "Base de Données INTRA" as BDD

== Scénario Nominal ==
activate CBS
activate BDD
CBS -> CBS : Génère numéro de compte + RIB
alt 2a. Erreur de génération
    CBS --> INTRA : Alerte d’échec
        activate INTRA
    INTRA --> Gestionnaire : Notification d’erreur
    activate Gestionnaire
else
    CBS --> INTRA : Envoie RIB et N° de compte
    INTRA -> BDD : Enregistrement dans la fiche client
    BDD --> INTRA : Confirmation d’enregistrement
    INTRA --> Gestionnaire : Affiche RIB et N° de compte
    
    alt 3a. Sauvegarde échoue
        INTRA -> BDD : Relance tentative
        
    end

    INTRA --> Gestionnaire : Accès au RIB possible (consultation/impression)
    deactivate Gestionnaire
    deactivate INTRA
    deactivate CBS
end

@enduml

